ALTER TABLE value_dimensions
  ADD COLUMN description VARCHAR(255) NOT NULL DEFAULT '' AFTER name,
  ADD COLUMN icon VARCHAR(64) NOT NULL DEFAULT '' AFTER description,
  ADD COLUMN color VARCHAR(16) NOT NULL DEFAULT '' AFTER icon;
